apiVersion: v1
name: proxyinjector
description: ProxyInjector chart that runs on kubernetes
version: v0.0.19
keywords:
  - Proxy
  - Authentication
  - kubernetes
home: https://github.com/stakater/ProxyInjector
maintainers:
- name: Stakater
  email: hello@stakater.com